services:
  compras:
    image: elixir:1.15.7-alpine
    container_name: compras
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Compras.Server
      AMQP_TO_RUN: Elixir.Libremarket.Compras.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname compras --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  ventas1:
    image: elixir:1.15.7-alpine
    container_name: ventas1
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"    
    environment:
      ROLE: PRINCIPAL
      SERVER_TO_RUN: Elixir.Libremarket.Ventas.Server
      AMQP_TO_RUN: Elixir.Libremarket.Ventas.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname ventas1 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  ventas2:
    image: elixir:1.15.7-alpine
    container_name: ventas2
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"    
    environment:
      ROLE: REPLICA
      SERVER_TO_RUN: Elixir.Libremarket.Ventas.Server
      AMQP_TO_RUN: Elixir.Libremarket.Ventas.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname ventas2 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  ventas3:
    image: elixir:1.15.7-alpine
    container_name: ventas3
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"    
    environment:
      ROLE: REPLICA
      SERVER_TO_RUN: Elixir.Libremarket.Ventas.Server
      AMQP_TO_RUN: Elixir.Libremarket.Ventas.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname ventas3 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  pagos1:
    image: elixir:1.15.7-alpine
    container_name: pagos1
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: PRINCIPAL
      SERVER_TO_RUN: Elixir.Libremarket.Pagos.Server
      AMQP_TO_RUN: Elixir.Libremarket.Pagos.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname pagos1 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  pagos2:
    image: elixir:1.15.7-alpine
    container_name: pagos2
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: REPLICA
      SERVER_TO_RUN: Elixir.Libremarket.Pagos.Server
      AMQP_TO_RUN: Elixir.Libremarket.Pagos.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname pagos2 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  pagos3:
    image: elixir:1.15.7-alpine
    container_name: pagos3
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: REPLICA
      SERVER_TO_RUN: Elixir.Libremarket.Pagos.Server
      AMQP_TO_RUN: Elixir.Libremarket.Pagos.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname pagos3 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  infracciones1:
    image: elixir:1.15.7-alpine
    container_name: infracciones1
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: PRINCIPAL
      SERVER_TO_RUN: Elixir.Libremarket.Infracciones.Server
      AMQP_TO_RUN: Elixir.Libremarket.Infracciones.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname infracciones1 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  infracciones2:
    image: elixir:1.15.7-alpine
    container_name: infracciones2
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: REPLICA
      SERVER_TO_RUN: Elixir.Libremarket.Infracciones.Server
      AMQP_TO_RUN: Elixir.Libremarket.Infracciones.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname infracciones2 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  infracciones3:
    image: elixir:1.15.7-alpine
    container_name: infracciones3
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: REPLICA
      SERVER_TO_RUN: Elixir.Libremarket.Infracciones.Server
      AMQP_TO_RUN: Elixir.Libremarket.Infracciones.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname infracciones3 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  envios1:
    image: elixir:1.15.7-alpine
    container_name: envios1
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: PRINCIPAL
      SERVER_TO_RUN: Elixir.Libremarket.Envios.Server
      AMQP_TO_RUN: Elixir.Libremarket.Envios.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname envios1 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  envios2:
    image: elixir:1.15.7-alpine
    container_name: envios2
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: REPLICA
      SERVER_TO_RUN: Elixir.Libremarket.Envios.Server
      AMQP_TO_RUN: Elixir.Libremarket.Envios.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname envios2 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  envios3:
    image: elixir:1.15.7-alpine
    container_name: envios3
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: REPLICA
      SERVER_TO_RUN: Elixir.Libremarket.Envios.Server
      AMQP_TO_RUN: Elixir.Libremarket.Envios.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname envios3 --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  api:
    image: elixir:1.15.7-alpine
    container_name: api
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      SERVER_TO_RUN: Elixir.Libremarket.Router
      PORT: "4000"
    ports:
      - "4000:4000"
    command: elixir --sname api --cookie ${SECRET} -S mix run --no-halt --no-compile
    stdin_open: true
    tty: true