services:
  compras:
    image: elixir:alpine
    container_name: compras
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Compras.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
    command: elixir --sname compras --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  ventas:
    image: elixir:alpine
    container_name: ventas
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"    
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Ventas.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
    command: elixir --sname ventas --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  pagos:
    image: elixir:alpine
    container_name: pagos
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Pagos.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
    command: elixir --sname pagos --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  infracciones:
    image: elixir:alpine
    container_name: infracciones
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Infracciones.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
    command: elixir --sname infracciones --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  envios:
    image: elixir:alpine
    container_name: envios
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Envios.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
    command: elixir --sname envios --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"