services:
  compras:
    image: elixir:1.15.7-alpine
    container_name: compras
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Compras.Server
      AMQP_TO_RUN: Elixir.Libremarket.Compras.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname compras --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  ventas:
    image: elixir:1.15.7-alpine
    container_name: ventas
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"    
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Ventas.Server
      AMQP_TO_RUN: Elixir.Libremarket.Ventas.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname ventas --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  pagos:
    image: elixir:1.15.7-alpine
    container_name: pagos
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Pagos.Server
      AMQP_TO_RUN: Elixir.Libremarket.Pagos.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname pagos --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  infracciones:
    image: elixir:1.15.7-alpine
    container_name: infracciones
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      ROLE: PRINCIPAL
      SERVER_TO_RUN: Elixir.Libremarket.Infracciones.Server
      AMQP_TO_RUN: Elixir.Libremarket.Infracciones.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname infracciones --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  envios:
    image: elixir:1.15.7-alpine
    container_name: envios
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      SERVER_TO_RUN: Elixir.Libremarket.Envios.Server
      AMQP_TO_RUN: Elixir.Libremarket.Envios.Consumer
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: amqp://ypznoogz:nqrvK3KQFu1BkqocK3WTTvQtQfqdWyga@shark.rmq.cloudamqp.com/ypznoogz
    command: elixir --sname envios --cookie ${SECRET} -S mix run --no-halt --no-compile
    user: "${DOCKER_UID}:${DOCKER_GID}"

  api:
    image: elixir:1.15.7-alpine
    container_name: api
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: "host"
    environment:
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      SERVER_TO_RUN: Elixir.Libremarket.Router
      PORT: "4000"
    ports:
      - "4000:4000"
    command: elixir --sname api --cookie ${SECRET} -S mix run --no-halt --no-compile
    stdin_open: true
    tty: true